spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://${DATABASE_HOST}/${DATABASE_NAME}
        username: ${DATABASE_USER}
        password: ${DATABASE_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
        properties:
          hibernate:
              dialect: org.hibernate.dialect.PostgreSQLDialect
              default_schema: public
server:
    port: 8080
